ARG THEGARII_VERSION=latest
ARG SF_VERSION=latest

FROM ghcr.io/streamingfast/thegarii:$THEGARII_VERSION as chain
FROM ghcr.io/streamingfast/firehose-arweave:$SF_VERSION

COPY --from=chain /app/thegarii /app/thegarii

COPY tools/firearweave/motd_node_manager /etc/motd
COPY tools/firearweave/scripts/. /usr/local/bin/
